### ISSUE TITLE
[Feature Request] YAML Macro system

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/PackageDev#110]
Example 1: a JavaScript syntax definition.

```yaml
%YAML 1.2
%TAG ! macro:myMacros:
---
contexts:
    
    main:
      - match: !word function
        scope: keyword
        push:
          - !meta meta.function.js
          - function-body
          - function-arguments
          - !identifier entity.name.function.js
```

myMacros.py:

```python
def meta(name):
    return [
        { 'meta_scope': name, },
        { 'match': r'(?=\S)', 'pop': True },
    ]

def word(match):
    return r'(?:%s){{b_after}}' % match

def identifier(scope):
    return [
        {
            'match': r'{{identifier}}{{b_after}}',
            'scope': scope,
            'pop': True,
        }
        { 'match': r'(?=\S)', 'pop': True },
    ]
```

Output:

```yaml
%YAML 1.2
---
contexts:

  main:
    - match: "function{{b_after}}"
      scope: keyword
      push:
        - - meta_scope: 'meta.function.js'
          - match: r'(?=\S)'
            pop: true
        - function-body
        - function-arguments
        - - match: '{{identifier}}{{b_after}}'
            scope: 'entity.name.function.js'
            pop: true,
          - match: '(?=\S)'
            pop: true
```

Example 2: a color scheme:

```yaml
%YAML 1.2
%TAG ! macro:colorSchemeMacros:
---
!remove variables:
  text: '#D8DEE9'
  mint: !hsb [ 114, 26, 78 ]

settings:
- name: Comment
  scope: comment, punctuation.definition.comment
  settings:
    foreground: !darken [ 0.5, !var text ]
- name: String
  scope: string
  settings:
    foreground: !var mint
```

---

This system uses YAML tags as macros. You can define any macros you like in a python module and refer to them using the `%TAG` directive. This is standards-compliant YAML, and the tag namespacing should forestall any conflicts.

We would need a build system to compile files with macros. In addition, we may want to provide specialized use cases, such as compiling a color scheme YAML file and then converting it to a plist.

I have a working implementation of the macro compiler in about 60 lines of python. Right now, it takes in a filename ending in `.source` and saves the result with that extension stripped. This API could be improved, particularly to make filename conversion more flexible. Once the API is hashed out, this feature is pretty much ready to go.
