### ISSUE TITLE
Capture highlighter does not ignore look-ahead groups

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#114]
![sample](https://user-images.githubusercontent.com/5332158/27838509-8690700e-60c1-11e7-8d09-2d5575e18401.gif)

via https://github.com/SublimeTextIssues/Core/issues/1796#issuecomment-312920245

**Comment by evandrocoan** [comment]
This is not a bug as we can see from this example, 

![sublime_shell](https://user-images.githubusercontent.com/5332158/27843220-baf5f9ec-60e7-11e7-975b-aa93351e73f2.gif)

Sublime Text is accepting capture groups inside look ahead. You can try it out with `(look)(?=(ing))\2`, which makes Sublime Text to correctly apply scopes for the capture group inside the look ahead:
```yaml
%YAML 1.2
---
name: test
scope: source.syntax_name

contexts:
  main:
    - match: '(look)(?=(ing))\2'
      captures:
        1: first.looking.assignment
        2: second.looking.assignment
      push:
        - meta_scope: third.looking.assignment
        - match: '(?=ing)'
          scope: forth.looking.assignment
        - match: ''
          pop: true
```
Sublime text is just not applying any scope to the text if the text is not eaten by the regular expression. Here bellow we see the scopes being correctly applied by Sublime Text one the ``\2` was introduced to the original regular expression.

![sublime_shell](https://user-images.githubusercontent.com/5332158/27843077-775ed0a6-60e6-11e7-9e53-5fcbbb4aa160.gif)

![sublime_shell](https://user-images.githubusercontent.com/5332158/27843137-01ec1116-60e7-11e7-9ed6-6a19b2f48500.gif)

1. https://regex101.com/r/UlNaHg/3
