### ISSUE TITLE
Is there a mechanism for embedding DSLs in existing highlighters?

### ISSUE THREAD

**Issue by StoneCypher** [SublimeText/PackageDev#174]
This is much more easily explained with an example, and I'll use the one I care about, but the question's sort of general by its nature

Some languages - recently including Javascript - have a mechanism either explicitly or sort of nudge-nudge-wink-wink generally meant for the creation of DSLs.  In Javascript, this is the `tagged template literal`.

Hi, I'm Troy McClure.  You may remember me from such films as that annoying ticket yesterday, or begging for help with easy things on IRC

For the sake of a short explanation that only I will find funny, let's say that I've come up with some domain specific language for describing pants.

So if you're *fancy*, in Javascript, these days, you're supposed to 

```javascript
const jeans = pants`holes   : yn
                    color   : [blue|black]
                    fit     : [tight|loose|jnco]
                    bottoms : [tight|flare|bell]`;
```

Now, obviously I can't expect Sublime's HTML/JS highlighter to know about or accomodate my awesome, category defining new pants DSL.  After all, we're not even releasing it until after the investor party next week

All the same, Sublime is my one true love, so when I'm spending the rest of my days working in `PantsL`, on those days I have to embed it on the web, I still want it hilit in all its glory.

Is there a way for me to write a highlighter which adds itself to some other highlighter?  Intrudes, as it were?

**Comment by keith-hall** [comment]
I believe the ST [YAML Macros plugin](https://forum.sublimetext.com/t/yaml-macros-easy-preprocessing-for-syntax-definitions/29039?u=kingkeith) was designed to do something similar to what you are requesting.

**Comment by FichteFoll** [comment]
I could probably add a reference to YAML Macros to the wiki.

**Comment by StoneCypher** [comment]
I confess I am completely whooshing here.

@keith-hall - is there any way I could jedi mind-trick you into showing me how to inject a thing into html/js that will take over pants`foo` (and just foo, i can do the rest) ?

I do not grasp what I am looking at.

**Comment by keith-hall** [comment]
You could try something like:

```yaml
%YAML 1.2
%TAG ! tag:yaml-macros:YAMLMacros.lib.extend:
---
!extend
_base: JavaScript.sublime-syntax
name: JavaScript with Pants DSL example

contexts: !merge
  literal-string-template: !prepend
    - include: pants-dsl

  pants-dsl-template-string:
    - match: (pants)(`)
      captures:
        1: variable.function.tagged-template.js
        2: punctuation.definition.string.template.begin.js
      set:
        - meta_include_prototype: false
        - meta_scope: string.template.js
        - match: "`"
          scope: punctuation.definition.string.template.end.js
          pop: true
        - match: '\$\{'
          captures:
            0: punctuation.definition.template-expression.begin.js
          push:
            - clear_scopes: 1
            - meta_scope: meta.template.expression.js
            - meta_content_scope: source.js.embedded.expression
            - match: '\}'
              scope: punctuation.definition.template-expression.end.js
              pop: true
            - match: (?=\S)
              push: expression
        - include: pants-dsl
        - include: string-content

  pants-dsl-pop:
    - match: (?=`)
      pop: true

  pants-dsl:
    - match: \bholes\b
      scope: variable.language.pants-dsl
      push: [pants-dsl-bool, pants-dsl-colon]
    - match: \bcolor\b
      scope: variable.language.pants-dsl
      push: [pants-dsl-color, pants-dsl-colon]
    - match: \bfit\b
      scope: variable.language.pants-dsl
      push: [pants-dsl-fit, pants-dsl-colon]
    - match: \bbottoms\b
      scope: variable.language.pants-dsl
      push: [pants-dsl-bottoms, pants-dsl-colon]

  pants-dsl-bool:
    - match: \b[yn]\b
      scope: support.constant.pants-dsl
      pop: true
    - include: pants-dsl-pop

  pants-dsl-color:
    - match: \b(?:blue|black)\b
      scope: support.constant.pants-dsl
      pop: true
    - include: pants-dsl-pop

  pants-dsl-fit:
    - match: \b(?:tight|loose|jnco)\b
      scope: support.constant.pants-dsl
      pop: true
    - include: pants-dsl-pop

  pants-dsl-bottoms:
    - match: \b(?:tight|flare|bell)\b
      scope: support.constant.pants-dsl
      pop: true
    - include: pants-dsl-pop

  pants-dsl-colon:
    - include: pants-dsl-pop
    - match: ':'
      scope: punctuation.separator.pants-dsl
      pop: true
```

I didn't have time to test it, but should work with the JS syntax as at build 3156.
