### ISSUE TITLE
Context completions in multi-push statements

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#201]
Currently context auto-completion works only, if the list of contexts is surrounded by brackets.

```
  cmd-generic:
    - match: (?=\S)
      push: [cmd-generic-end, cmd-generic-name]
```

It would be useful to have auto-competions for contexts like `cmd-generic-end` in following list styles as well.

```
  cmd-generic:
    - match: (?=\S)
      push: 
        - cmd-generic-end
        - cmd-generic-name
```
