### ISSUE TITLE
A list of missing built-in commands.

### ISSUE THREAD

**Issue by deathaxe** [SublimeText/PackageDev#268]
The following commands were found in the Default.sublime-package which don't exist in one of the python command lists.

```
all_command_classes = [
    application_command_classes,
    window_command_classes,
    text_command_classes]
```

Therefore they can be considered built-in. Some of them are valid only in special situations such as the find_in_files panels etc. Not sure whether all of them need to be added to the completions.

```
add_directory:
    command_type: text
    doc_string: Opens a dialog box to prompt for a folder to the Where Input in the Find in Files panel.
add_where_snippet:
    command_type:
    doc_string:
build_systems:
    command_type:
    doc_string:
clear_location:
    command_type:
    doc_string:
clear_recent_files:
    command_type:
    doc_string:
clear_recent_projects_and_workspaces:
    command_type:
    doc_string:
clone_file:
    command_type:
    doc_string:
close:
    command_type:
    doc_string:
close_all:
    command_type:
    doc_string:
close_window:
    command_type:
    doc_string:
console_python_version:
    command_type:
    doc_string:
detect_indentation:
    command_type:
    doc_string:
dictionaries:
    command_type:
    doc_string:
exit:
    command_type:
    doc_string:
expand_selection_to_paragraph:
    command_type:
    doc_string:
file_types:
    command_type:
    doc_string:
find_all:
    command_type:
    doc_string:
focus_side_bar:
    command_type:
    doc_string:
fold_tag_attributes:
    command_type:
    doc_string:
goto_symbol_in_project:
    command_type:
    doc_string:
hide_popup:
    command_type:
    doc_string:
open_recent_file:
    command_type:
    doc_string:
open_recent_folder:
    command_type:
    doc_string:
open_recent_project_or_workspace:
    command_type:
    doc_string:
open_url:
    command_type:
    doc_string:
prompt_open:
    command_type:
    doc_string:
purchase_license:
    command_type:
    doc_string:
remove_folder:
    command_type:
    doc_string:
remove_license:
    command_type:
    doc_string:
reopen:
    command_type:
    doc_string:
reopen_last_file:
    command_type:
    doc_string:
replace_all:
    command_type:
    doc_string:
replace_completion_with_auto_complete:
    command_type:
    doc_string:
replace_next:
    command_type:
    doc_string:
reveal_in_side_bar:
    command_type:
    doc_string:
reveal_link_source:
    command_type:
    doc_string:
revert:
    command_type:
    doc_string:
save_macro:
    command_type:
    doc_string:
set_build_system:
    command_type:
    doc_string:
set_line_ending:
    command_type:
    doc_string:
set_setting:
    command_type:
    doc_string:
show_about_window:
    command_type:
    doc_string:
show_changelog:
    command_type:
    doc_string:
show_license_window:
    command_type:
    doc_string:
show_progress_window:
    command_type:
    doc_string:
sublime_merge_blame_file:
    command_type:
    doc_string:
sublime_merge_file_history:
    command_type:
    doc_string:
sublime_merge_folder_history:
    command_type:
    doc_string:
sublime_merge_line_history:
    command_type:
    doc_string:
sublime_merge_open_repo:
    command_type:
    doc_string:
toggle_case_sensitive:
    command_type:
    doc_string:
toggle_distraction_free:
    command_type:
    doc_string:
toggle_menu:
    command_type:
    doc_string:
toggle_preserve_case:
    command_type:
    doc_string:
toggle_regex:
    command_type:
    doc_string:
toggle_save_all_on_build:
    command_type:
    doc_string:
toggle_show_open_files:
    command_type: window
    doc_string:
toggle_whole_word:
    command_type:
    doc_string:
trim_trailing_white_space:
    command_type:
    doc_string:
update_check:
    command_type:
    doc_string:
upgrade_license:
    command_type:
    doc_string:
wrap_lines:
    command_type:
    doc_string:
```
