### ISSUE TITLE
"Convert to YAML" converts cyrillic characters to unicode-escaped

### ISSUE THREAD

**Issue by atomichammer** [SublimeText/PackageDev#276]
Converting an *.tmlangauage file which contains cyrillic text in UTF-8 to YAML results in this text being converted to unicode-escaped sequence.
For example:
```xml
<dict>
    <key>comment</key>
    <string>ключевые слова, которые формируют или прерывают цикл</string>
    <key>match</key>
    <string>(?i)\b(elif|else|for|if|while|break|continue|return|end)\b</string>
    <key>name</key>
    <string>keyword.control.flow.mac</string>
</dict>
```
converts to
```yaml
- comment: "\u043A\u043B\u044E\u0447\u0435\u0432\u044B\u0435 \u0441\u043B\u043E\u0432\
    \u0430, \u043A\u043E\u0442\u043E\u0440\u044B\u0435 \u0444\u043E\u0440\u043C\u0438\
    \u0440\u0443\u044E\u0442 \u0438\u043B\u0438 \u043F\u0440\u0435\u0440\u044B\u0432\
    \u0430\u044E\u0442 \u0446\u0438\u043A\u043B"
  match: (?i)\b(elif|else|for|if|while|break|continue|return|end)\b
  name: keyword.control.flow.mac
```
