### ISSUE TITLE
Warn wrong dict/list type mistakes in .sublime-syntax

### ISSUE THREAD

**Issue by jfcherng** [SublimeText/PackageDev#299]
@genericptr is a newbie learning `.sublime-syntax` and he encountered a "weird" situation that his rule was not working at all. (chat: https://discord.com/channels/280102180189634562/280157083356233728/733181451616518184)

```yaml
  main:
    - match: \b(?i:(function|procedure)+)\b\s+(\w+)
      captures:
        - 1: keyword.control.pascal
        - 3: entity.name.function.pascal
```

It took me a while to figure out that he was using a list in `captures` rather than a dict. Or sometimes similarly, people may wrongly do `meta_scope:` rather than `- meta_scope:` etc...

---

It could be a common mistake and could be hard to find out at the first glance. So I guess it would be good if those dict/list mistakes can be warned.
