### ISSUE TITLE
Perform data type checks before conversion

### ISSUE THREAD

**Issue by wadetb** [SublimeText/PackageDev#49]
This syntax looks mostly right and builds fine using AAAPackageDev.

``` yaml
# [PackageDev] target_format: plist, ext: tmLanguage

---
name: MySyntax
fileTypes: [txt]
scopeName: text.mysyntax
uuid: 7ce133ea-e34b-47d9-a03c-341293337c88

patterns:
    name: keyword.mysyntax
    match: (.*)
```

But when loaded in ST3, it gives this obscure error:

> Error loading syntax file "Packages/Sublime-Text-3-CSV-Plugin/AdvancedCSV.tmLanguage": boost::bad_any_cast: failed conversion using boost::any_cast

The issue is the missing `-` before the `name` keyword in `patterns`.  The plist is generated without an `<array>` node enclosing the patterns, leading to the obscure error message.

Would it be possible to validate the YAML for proper structure when compiling tmLanguage files?
