### ISSUE TITLE
[feature request] highlight relevant capture group

### ISSUE THREAD

**Issue by keith-hall** [SublimeText/PackageDev#92]
when writing syntax definitions, one quite often uses multiple capture groups. It can get quite tricky to find/remember where each group starts and which number it is.
I therefore propose that we add functionality similiar to how the syntax test highlighting helper works, and when the caret is on a `captures: n:` line in a `sublime-syntax` file, that the relevant group be highlighted in the corresponding `match:` line

```yaml
  - match: ((a)?(b)cde(fgh))(ij)
    captures:
      1: where is capture group 1 again?
```
