### ISSUE TITLE
CI for syntax tests using syntect

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/PackageDev#98]
Add CI (using Travis CI) for syntax tests. There is [UnitTesting](https://github.com/randy3k/UnitTesting), which also supports running syntax tests (which I never tested), but to me it seems like using [syntect](https://github.com/trishume/syntect) is better. I don't see myself writing tests for the Python plugins and their integration into ST in the near future.

I'll document the current progress and obstacles in this issue.

### Status

~~Blocked by: https://github.com/trishume/syntect/issues/46~~

Not mature enough yet (quite a few false-positives) but could be set up as a non-failing command for travis.

**Comment by FichteFoll** [comment]
### Current `.travis.yml` (untested)

```yaml
language: rust

rust:
  - stable

addons:
  apt:
    packages:
      - python3 # ST3 uses py3.3, but we're only running flake8 anyway

install:
  - pip install flake8==3.3.0
  - cargo install syntect --git https://github.com/trishume/syntect --example syntest
  - export PATH="$HOME/.cargo/bin:$PATH"

script:
  - python3 -m flake8 -v
  # - TODO syntest ...
```

We can use the apt addon to install Python 3 into the container-based architecture, but not Rust, so our main "language" will be switching to `rust`.

The `syntest` example is not included in the latest release on crates.io (1.2.0), which is why we point it to the git repo on Github and build from `master`.

---

### Running syntest

`syntest` accepts two parameters, one for the syntax test files and one for syntax files. I was able to run it with `syntest Packages/PackageDev Packages` from `~/.config/sublime-text-3`, which seems to be The Way To Go™ for now. I'm not exactly happy with it, but we'll manage.

I'm thinking of setting up symlinks in a CI-specific sub-directory that will establish the directory structure that `syntest` expects according to our paths in the syntax test files.

Additionally, we depend on the `XML/XML.sublime-syntax` and `JavaScript/JSON.sublime-syntax` syntaxes. We might have to pull the sublimehq/Packages repo (master or release tag) into the testing directory structure mentioned above.

---

Blocked by: https://github.com/trishume/syntect/issues/46
